Делегаты и события
De-Len/2_Semester-Lab6-Delegates_events pull request #1
Opened 2024-03-21 10:07 UTC by prince-de-len

2024-03-21 17:11 UTC, Hamjoshua requested changes
Ревью

2024-03-21 17:11 UTC, Hamjoshua commented on Program.cs
> +        if (int.TryParse(Console.ReadLine(), out choice) && choice >= 1 && choice <= 5)
В 843 строке завелся монстр
Ты не должен бояться того, что choice выйдет за рамки. Программа должна просто вывести "хэндлеры не вывезли движуху, ваш choice гав-"
Ну ты понял

2024-03-21 17:11 UTC, Hamjoshua commented on Program.cs
> +        if (int.TryParse(Console.ReadLine(), out choice) && choice >= 1 && choice <= 5)
Похвально уводить хэндлеры в сторону, когда им в лицо летит запрос гав-
Но при расширении тебе придется ручками настраивать условие для choice
О том, когда стоит прервать цепочку передачи запроса, читай на стр 249 EASY книги по паттернам

2024-03-21 17:11 UTC, Hamjoshua commented on Program.cs
> +        if (int.TryParse(Console.ReadLine(), out choice) && choice >= 1 && choice <= 5)
И у тебя кстати уже все прописано: в switch стоит default. Если попадет нелепое значение, он переведет на default

2024-03-21 17:23 UTC, prince-de-len commented on Program.cs
> +        if (int.TryParse(Console.ReadLine(), out choice) && choice >= 1 && choice <= 5)
Да, точняк)

2024-03-22 02:54 UTC, Hamjoshua requested changes

2024-03-22 02:54 UTC, Hamjoshua commented on Program.cs
> +            Console.WriteLine("Буквы запрещены.");
Досадно, когда из-за одной ошибки ты не можешь произвести вычисления. Сделай меню в цикле while

2024-03-22 02:54 UTC, Hamjoshua commented on Program.cs
> +        IEvent ev = null;
Сокращенные переменные не есть гуд. Если будет жаловаться на "event", пиши "@event"

2024-03-22 02:54 UTC, Hamjoshua commented on Program.cs
> +                    catch (Exception ex)
Ну и этот прикол поправить надо

2024-03-22 05:05 UTC, Hamjoshua approved these changes

2024-03-22 05:08 UTC, merged